[package]
name = "test-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
bluer = {version="0.17.3", features=["bluetoothd"]}
env_logger = "0.11.5"
futures = "0.3.31"
tokio = { version = "1.41.0", features = ["rt-multi-thread", "macros", "io-std"] }
uuid = "1.11.0"
